 - name: Install the MySQL packages
   apt: 
    name: ['mysql-server','python3-mysqldb']
    state: latest
    update_cache: yes

 - name: Update MySQL root password for all root accounts
   mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
   with_items:
     - 127.0.0.1
     - ::1
     - localhost

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

 - name: Ensure Anonymous user(s) are not in the database
   mysql_user: name='' host=localhost state=absent

 - name: Remove the test database
   mysql_db: name=test state=absent
   notify:
     - Restart MySQL
